[package]
name = "conductor"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.1"
aws-sdk-cloudformation = "0.26.0"
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
controller = { path = "../tembo-operator", package = "controller" }
env_logger = "0.11"
futures = "0.3"
k8s-openapi = { version = "0.22.0", features = ["v1_28", "schemars"] }
log = "0.4"
pgmq = "0.16.1"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.28.0", features = ["full"] }
actix-web = "4.3.0"
actix-web-opentelemetry = { version = "0.18.0", features = [
  "metrics-prometheus",
] }
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry_sdk = { version = "0.20", features = [
  "metrics",
  "rt-tokio-current-thread",
] }
opentelemetry-prometheus = "0.13" #otel-prometheus needs to support the same version as otel and otel_sdk
prometheus = "0.13"
sqlx = "0.6.3"
anyhow = "1.0"
serde_yaml = "0.9.34"
reqwest = { version = "0.12", features = ["json"] }

[dependencies.kube]
features = ["runtime", "client", "derive"]
version = "0.91.0"


[dev-dependencies]
rand = "0.8.5"
