name: Cargo Build

on:
  push:
    tags:
      - v[0-9]+.*-beta

jobs:

  cargo_build:
    name: Cargo build
    runs-on: ubuntu-20.04
    container:
      image: quay.io/tembo/muslrust:1.71.0-stable
      #needs:
      # - find_directories
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Cargo build
        working-directory: ./tembo-cli
        id: cargo_build
        run: |
          set -x
          cargo build --release --target=x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.name }}
          workspaces: |
            ${{ matrix.path }}

