name: Cargo Build

on:
  push:
    tags:
      - v[0-9]+.*-beta

jobs:

  cargo_build:
    name: Cargo build
    runs-on: ubuntu-20.04
    container:
      image: quay.io/tembo/muslrust:1.71.0-stable
      #needs:
      # - find_directories
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup tools
        id: setup_tools
        run: |
          set -x
          apt-get update && apt-get install -y gh

      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

      - name: Cargo build
        working-directory: ./tembo-cli
        id: cargo_build
        run: |
          set -x
          cargo build --release --target=x86_64-unknown-linux-musl

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/x86_64-unknown-linux-musl
            #asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
