name: Release tembo

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*-beta

jobs:

  cargo_build:
    name: Cargo build
    runs-on: ubuntu-20.04
    container:
      image: quay.io/tembo/muslrust:1.71.0-stable
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Cargo build
        working-directory: ./tembo-cli
        id: cargo_build
        run: |
          set -x
          cargo build --release --target=x86_64-unknown-linux-musl
          target/x86_64-unknown-linux-musl/release/tembo --version

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tembo-cli/target/x86_64-unknown-linux-musl/release/tembo
          asset_name: tembo-cli-${{ github.ref}}-x86_64-unknown-linux-musl
          prerelease: true
          tag: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
